apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: arboureric/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.ts'
            dest: .
    - image: arboureric/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.ts'
            dest: .
