apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-dev-304820
  artifacts:
    - image: us.gcr.io/ticketing-dev-304820/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-304820/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-304820/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-304820/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-304820/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-304820/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.ts'
            dest: .
